name: automaton_studio_v2
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  arrow_path: ^2.0.0
  country_icons: ^2.0.2
  masked_text: ^0.0.6
  path_provider: ^2.0.2
  json_annotation: ^4.1.0
  vector_math: ^2.1.0
  shared_preferences: ^2.0.11
  flutter_colorpicker: ^1.0.3
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/

  fonts:
    - family: Baloo
      fonts:
        - asset: lib/assets/fonts/BalooBhaijaan2-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/BalooBhaijaan2-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/BalooBhaijaan2-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/BalooBhaijaan2-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/BalooBhaijaan2-ExtraBold.ttf
          weight: 800
